
# render.yaml
services:
  - type: web
    name: jarvis-assistant
    env: python
    buildCommand: |
      apt-get update && apt-get install -y espeak-ng
      pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
