services:
  - type: web
    name: jarvis-assistant
    env: python
    plan: free
    buildCommand: ./build.sh && pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PORT
        value: 10000
    runtime: python
